version: '3.3'
services:  
  demo-transitions:
    container_name: demo-transitions
    ports:
      - 3000:3000
    build: 
      context: ./
      dockerfile: ./Dockerfile 
    volumes: 
      - ./:/src 